### ISSUE TITLE
ELF&PE - 버전별, 옵션별 샘플 파일

### ISSUE THREAD

**Issue by seleuchel** [InformationSecurity119/2019_KUCIS_Project_checksec.py#57]

**Comment by koyokr** [comment]
병합할 때 샘플들은 tests/binaries 여기에 넣어주세요

**Comment by seleuchel** [comment]
PE
![image](https://user-images.githubusercontent.com/37205198/69497025-b39a7800-0f1b-11ea-8907-57deeb87e1b2.png)

ELF
![image](https://user-images.githubusercontent.com/37205198/69497029-bdbc7680-0f1b-11ea-9a19-dd122907e373.png)

샘플파일 준비완료!
